language: cpp
os: linux
compiler: gcc
sudo: true
dist: trusty
cache:
  ccache: true
  directories:
  - ${HOME}/.ccache

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev

env:
  global:
  - USE_C_COMPILERACHE=1
  - C_COMPILERACHE_COMPRESS=1
  - C_COMPILERACHE_MAXSIZE=200M
  - C_COMPILERACHE_CPP2=1
  - LOCAL=${HOME}/.local
  - PATH=${LOCAL}/bin:${PATH}
  - BUILD_TYPE='Debug'
  - CXX_COMPILER='ccache g++-7'

before_script:
- export CXX="${CXX_COMPILER}"
- cmake --version
- ${CXX} --version
- wget -O boost_1_64_0.tar.gz https://sourceforge.net/projects/boost/files/boost/1.64.0/boost_1_64_0.tar.gz/download
- tar xzf boost_1_64_0.tar.gz
- cd boost_1_64_0
- ./bootstrap.sh --with-libraries=system,thread,context,coroutine
- mkdir build
- ./b2 --build-dir=build
- sudo ./b2 --build-dir=build install
- cd ${TRAVIS_BUILD_DIR}
- mkdir -p ${TRAVIS_BUILD_DIR}/build
- cd ${TRAVIS_BUILD_DIR}/build
- cmake -DCMAKE_VERBOSE_MAKEFILE=1 -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DRESOURCE_POOL_BUILD_TESTS=ON -DRESOURCE_POOL_BUILD_EXAMPLES=ON -DRESOURCE_POOL_BUILD_BENCHMARKS=ON ${TRAVIS_BUILD_DIR}

script:
- make -j $(nproc)
- ctest -V -j $(nproc)
- cat ${TRAVIS_BUILD_DIR}/build/external/src/google_benchmark-stamp/google_benchmark-configure-*.log

after_success:
- git clone https://github.com/SimonKagstrom/kcov.git
- mkdir kcov/build
- cd kcov/build
- cmake -DCMAKE_INSTALL_PREFIX:PATH=${LOCAL} ..
- make -j $(nproc)
- make install
- cd ../..
- kcov --coveralls-id=${TRAVIS_JOB_ID} --include-path ${TRAVIS_BUILD_DIR}/include ${TRAVIS_BUILD_DIR}/build/kcov ${TRAVIS_BUILD_DIR}/build/tests/resource_pool_test
